[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "clarifai-shared"
version = "0.1.0"
description = "Shared utilities and modules for ClarifAI services."
dependencies = []

[tool.ruff]
# Service-specific ruff config
