[tool.poetry]
name = "scheduler"
version = "0.1.0"
description = "Task scheduling service for periodic jobs and background processing"
authors = ["ClarifAI Team"]
readme = "README.md"
packages = [{include = "scheduler"}]

[tool.poetry.dependencies]
python = "^3.11"
# Shared package
clarifai-shared = {path = "../../shared", develop = true}
# Scheduling
apscheduler = "^3.10.0"
celery = "^5.3.0"
# Message queue
pika = "^1.3.0"
# Configuration and utilities
pydantic = "^2.7.0"
python-dotenv = "^1.0.0"
croniter = "^2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-asyncio = "^0.23.0"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"