name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
      docker: ${{ steps.filter.outputs.docker }}
      docker-compose: ${{ steps.filter.outputs.docker-compose }}
    steps:
    # You only need a basic checkout. The filter uses the API, not the local git repo.
    - uses: actions/checkout@v4

    - name: Identify changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        # The action handles it automatically via the GitHub API.
        filters: |
          python:
            - '**/*.py'
            - '**/pyproject.toml'
            - '**/uv.lock'
          docker:
            - '**/Dockerfile*'
            - '**/.dockerignore'
            - 'services/**'
          docker-compose:
            - 'docker-compose*.yml'
            - '.env.example'


  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    needs: changes # Needs the output from the changes job
    if: needs.changes.outputs.python == 'true' # Only run if Python files changed
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: pip install uv
        
    - name: Cache Python virtual environment
      uses: actions/cache@v4
      id: cache-venv
      with:
        path: .venv
        key: ${{ runner.os }}-python-3.11-${{ hashFiles('**/uv.lock') }}
        
    - name: Install dependencies
      # No cache-hit check needed; uv handles this efficiently.
      run: |
        uv venv
        uv pip install -e ".[dev]" -e ./shared -e ./services/*
        
    - name: Run Ruff linter and formatter
      run: |
        .venv/bin/ruff check .
        .venv/bin/ruff format --check .
      
    - name: Run type checking
      run: |
        .venv/bin/mypy .
        .venv/bin/check-annotations . --config-section tool.coverage.run --config-exclude-key omit
    - name: Upload venv artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-venv
        path: .venv

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [lint-and-format]
    if: needs.changes.outputs.python == 'true'
    
    steps:
    - uses: actions/checkout@v4

    - name: Download venv artifact
      uses: actions/download-artifact@v4
      with:
        name: python-venv
        path: .venv

    - name: Run Bandit security scan
      run: .venv/bin/bandit -r . -c pyproject.toml

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [changes, lint-and-format] # Depends on linting and the changes job
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && needs.changes.outputs.python == 'true')

    env:
      NEO4J_PASSWORD: fake_test_neo4j_password_123
      POSTGRES_PASSWORD: fake_test_postgres_password_456

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download venv artifact
      uses: actions/download-artifact@v4
      with:
        name: python-venv
        path: .venv

    - name: Run tests
      run: |
        export PYTHONPATH=$(pwd)
        .venv/bin/pytest -v --tb=short \
          tests/ \
          shared/tests/ \
          services/aclarai-core/tests/ \
          services/aclarai-ui/tests/ \
          services/scheduler/tests/ \
          services/vault-watcher/tests/

  docker-build:
    name: Docker Build Validation
    runs-on: ubuntu-latest
    needs: [changes, test] # Depends on tests passing and the changes job
    if: needs.changes.outputs.docker == 'true' # Only run if Docker-related files changed
    strategy:
      matrix:
        service: [aclarai-core, vault-watcher, scheduler, aclarai-ui]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      # This simplified build command is sufficient for validation.
      # It doesn't need complex caching logic for a simple build check.
      run: >
        docker build --tag aclarai-${{ matrix.service }}:test -f ./services/${{ matrix.service }}/Dockerfile .

  docker-compose-validation:
    name: Docker Compose Validation
    runs-on: ubuntu-latest
    needs: [changes, test]
    if: needs.changes.outputs.docker-compose == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Validate docker-compose
      run: |
        cp .env.example .env
        docker compose config --quiet