name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
      docker: ${{ steps.filter.outputs.docker }}
      docker-compose: ${{ steps.filter.outputs.docker-compose }}
    steps:
    - name: Checkout PR Code
      # This checks out the PR's code as a detached HEAD. This is fine.
      uses: actions/checkout@v4

    - name: Fetch Target Branch (${{ github.base_ref }})
      # This is the key step. We manually fetch ONLY the target branch
      # (e.g., 'main') and create a local branch with the same name.
      run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}:${{ github.base_ref }}

    - name: Identify changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        # Now we can be certain that the base ref exists for comparison.
        base: ${{ github.base_ref }}
        filters: |
          python:
            - '**/*.py'
            - '**/pyproject.toml'
            - '**/uv.lock'
            - 'shared/**'
          docker:
            - '**/Dockerfile*'
            - '**/.dockerignore'
            - 'services/**'
          docker-compose:
            - 'docker-compose*.yml'
            - '.env.example'

    # This debug step will now succeed.
    - name: Verify Git State
      run: |
        echo "--- Verifying Git State ---"
        echo "--> All local branches:"
        git branch -a
        echo "--> Manual Git Diff against ${{ github.base_ref }}:"
        git diff --name-only ${{ github.base_ref }}...HEAD
        echo "--------------------------"

  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    needs: changes # Needs the output from the changes job
    if: needs.changes.outputs.python == 'true' # Only run if Python files changed
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: pip install uv
        
    - name: Cache Python virtual environment
      uses: actions/cache@v4
      id: cache-venv
      with:
        path: .venv
        key: ${{ runner.os }}-python-3.11-${{ hashFiles('**/uv.lock') }}
        
    - name: Install dependencies
      # No cache-hit check needed; uv handles this efficiently.
      run: |
        uv venv
        uv pip install -e ".[dev]" -e ./shared -e ./services/*
        
    - name: Run Ruff linter and formatter
      run: |
        .venv/bin/ruff check .
        .venv/bin/ruff format --check .
      
    - name: Run MyPy type checking
      run: .venv/bin/mypy . || true

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [changes, lint-and-format] # Depends on linting and the changes job
    if: needs.changes.outputs.python == 'true' # Match the condition of its dependency
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Restore venv cache
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-python-3.11-${{ hashFiles('**/uv.lock') }}
        
    - name: Run Bandit security scan
      # Bandit is installed as a dev dependency, so it's already in the cached venv
      run: .venv/bin/bandit -r . -c pyproject.toml

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [changes, lint-and-format] # Depends on linting and the changes job
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && needs.changes.outputs.python == 'true')

    env:
      NEO4J_PASSWORD: fake_test_neo4j_password_123
      POSTGRES_PASSWORD: fake_test_postgres_password_456
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # '0' means fetch all history for all branches and tags, to give the runner the data it needs to find commit A and correctly identify that the files changed in your PR are the ones modified
        fetch-depth: 0

    - name: Restore venv cache
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-python-3.11-${{ hashFiles('**/uv.lock') }}
        
    - name: Run tests
      run: |
        # Set PYTHONPATH to include the project root for pytest discovery
        export PYTHONPATH=$(pwd)
        .venv/bin/pytest -v --tb=short tests/ shared/tests/ services/

  docker-build:
    name: Docker Build Validation
    runs-on: ubuntu-latest
    needs: [changes, test] # Depends on tests passing and the changes job
    if: needs.changes.outputs.docker == 'true' # Only run if Docker-related files changed
    strategy:
      matrix:
        service: [aclarai-core, vault-watcher, scheduler, aclarai-ui]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      # This simplified build command is sufficient for validation.
      # It doesn't need complex caching logic for a simple build check.
      run: >
        docker build --tag aclarai-${{ matrix.service }}:test ./services/${{ matrix.service }}

  docker-compose-validation:
    name: Docker Compose Validation
    runs-on: ubuntu-latest
    needs: [changes, test]
    if: needs.changes.outputs.docker-compose == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Validate docker-compose
      run: |
        cp .env.example .env
        docker compose config --quiet