name: Copilot Environment Setup
# This workflow is triggered manually and is used to configure the development
# environment that GitHub Copilot uses for providing context-aware code suggestions.
on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # The python version is specified in the root pyproject.toml.
          python-version: '3.11'

      - name: Install uv package manager
        run: pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install All Monorepo Dependencies
        # This single command installs dependencies for the entire monorepo workspace.
        # The `[tool.uv.workspace]` section in the root pyproject.toml tells `uv`
        # to recognize and install dependencies from all member packages (services/* and shared/).
        # The `.[dev]` part installs the root project's dependencies plus its optional 'dev' dependencies.
        run: uv pip install -e ".[dev]"
